#!/usr/bin/env bash

if [ -v $(command -v helm) ]; then
    echo "Helm is not installed, cannot continue"
    exit 0
fi

if [ -v $(command -v kubectl) ]; then
    echo "Kubectl is not installed, cannot continue"
    exit 0
fi

helm template ${PWD} | kubectl apply -f -