---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.namespace }}-deploy-account
  namespace: {{ .Values.namespace }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.namespace }}-deploy-account
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.namespace }}-deploy-account
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.namespace }}-deploy-account
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.namespace }}-deploy-account
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.namespace }}-deploy-account
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods","pods/exec"]
    verbs: ["create","get","update","delete","list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    resourceNames: ["{{ .Values.namespace }}-database", "{{ .Values.namespace }}-dovecot"]
    verbs: ["get","update","patch","delete"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.namespace }}-deploy-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namespace }}-deploy-account
subjects:
  - kind: ServiceAccount
    name: {{ .Values.namespace }}-deploy-account
    namespace: {{ .Values.namespace }}
---